version: '3.1'

services:
    postgres:
      image: postgres
      restart: always
      environment:
        POSTGRES_USER: test
        POSTGRES_PASSWORD: test
        POSTGRES_DATABASE: test
        POSTGRES_ROOT_PASSWORD: test
        pgdata: data-pstgresql
      ports:
      - "5432:5432"
      volumes:
      - data-pstgresql:/data
      - ./sql:/docker-entrypoint-initdb.d

    go-csv-reader-service:
      restart: always
      environment:
        TC_GRPC_SERVER_URL: go-storage-service:50051
      container_name: go-csv-reader-service
      image: "docker.go-example.com/go-csv-reader-service:latest"
      build:
        context: ./file-reader-service
      ports:
      - "9000:9000"

    go-storage-service:
      restart: always
      environment:
        TC_DATABASE: test
        TC_USER: test
        TC_PASSWORD: test
        TC_HOST: postgres
      container_name: go-storage-service
      image: "docker.go-example.com/go-storage-service:latest"
      build:
        context: ./storage-service

volumes:
    data-pstgresql:
